[#if build.buildDefinition.customConfiguration.get('custom.cc.baselinelabeller.enabled')?has_content]
    [@ui.bambooInfoDisplay titleKey='Baseline Promoter']
        [@ww.label label='Successful build Promotion Level' ]
           [@ww.param name='value']${build.buildDefinition.customConfiguration.get('custom.cc.baselinelabeller.pl.success')?if_exists}[/@ww.param]
        [/@ww.label]
        [@ww.label label='Failed build Promotion Level' ]
           [@ww.param name='value']${build.buildDefinition.customConfiguration.get('custom.cc.baselinelabeller.pl.fail')?if_exists}[/@ww.param]
        [/@ww.label]
        [@ww.label label='Recommend baseline' ]
           [@ww.param name='value']${build.buildDefinition.customConfiguration.get('custom.cc.baselinelabeller.recommend')?if_exists}[/@ww.param]
        [/@ww.label]
    [/@ui.bambooInfoDisplay]
[/#if]