[#if build.buildDefinition.customConfiguration.get('custom.repository.cc.clearcaseType') == "Base" ]
    [@ui.bambooInfoDisplay titleKey='ClearCase - Settings']
        [@ww.label label='ClearCase Type' ]
           [@ww.param name='value']${repository.getClearCaseType()?if_exists}[/@ww.param]
        [/@ww.label]
        [@ww.label label='Snapshot View Location' ]
           [@ww.param name='value']${repository.getBaseViewLocation()?if_exists}[/@ww.param]
        [/@ww.label]
        [@ww.label label='VOB Directory' ]
           [@ww.param name='value']${repository.getVobDir()?if_exists}[/@ww.param]
        [/@ww.label]
        [@ww.label label='Branch' ]
           [@ww.param name='value']${repository.getBranch()?if_exists}[/@ww.param]
        [/@ww.label]        
        [@ww.label label='Automatic Create' ]
           [@ww.param name='value']${build.buildDefinition.customConfiguration.get('custom.repository.cc.autocreate')?if_exists}[/@ww.param]
        [/@ww.label]
        [@ww.label label='Disable Automatic Update' ]
           [@ww.param name='value']${build.buildDefinition.customConfiguration.get('custom.repository.cc.disableUpdate')?if_exists}[/@ww.param]
        [/@ww.label]
        [@ww.label label='Build Prefix' ]
           [@ww.param name='value']${repository.getBuildPrefix()?if_exists}[/@ww.param]
        [/@ww.label]
        [@ww.label label='View Tag' ]
           [@ww.param name='value']${repository.getViewTag()?if_exists}[/@ww.param]
        [/@ww.label]
        [@ww.label label='View Storage Directory' ]
           [@ww.param name='value']${repository.getViewStorageDir()?if_exists}[/@ww.param]
        [/@ww.label]               
        [@ww.label label='Dynamic View' ]
           [@ww.param name='value']${build.buildDefinition.customConfiguration.get('custom.repository.cc.dynamicView')?if_exists}[/@ww.param]
        [/@ww.label]
	    [@ww.label label='Load Rules' ]
           [@ww.param name='value']${repository.getLoadRules()?if_exists}[/@ww.param]
        [/@ww.label]
    [/@ui.bambooInfoDisplay]

[/#if]

[#if build.buildDefinition.customConfiguration.get('custom.repository.cc.clearcaseType') == "UCM" ]
    [@ui.bambooInfoDisplay titleKey='ClearCase - Settings']
        [@ww.label label='ClearCase Type' ]
           [@ww.param name='value']${repository.getClearCaseType()?if_exists}[/@ww.param]
        [/@ww.label]
        [@ww.label label='Snapshot View Location' ]
           [@ww.param name='value']${repository.getBaseViewLocation()?if_exists}[/@ww.param]
        [/@ww.label]
        [@ww.label label='VOB Directory' ]
           [@ww.param name='value']${repository.getVobDir()?if_exists}[/@ww.param]
        [/@ww.label]
        [@ww.label label='Branch' ]
           [@ww.param name='value']${repository.getBranch()?if_exists}[/@ww.param]
        [/@ww.label]
        [@ww.label label='Project Name' ]
           [@ww.param name='value']${repository.getProjectName()?if_exists}[/@ww.param]
        [/@ww.label]
        [@ww.label label='Main Component' ]
           [@ww.param name='value']${repository.getMainComponent()?if_exists}[/@ww.param]
        [/@ww.label]
        [@ww.label label='Integration Stream' ]
           [@ww.param name='value']${repository.getIntStream()?if_exists}[/@ww.param]
        [/@ww.label]
        [@ww.label label='Automatic Create' ]
           [@ww.param name='value']${build.buildDefinition.customConfiguration.get('custom.repository.cc.autocreate')?if_exists}[/@ww.param]
        [/@ww.label]
        [@ww.label label='Disable Automatic Update' ]
           [@ww.param name='value']${build.buildDefinition.customConfiguration.get('custom.repository.cc.disableUpdate')?if_exists}[/@ww.param]
        [/@ww.label]
        [@ww.label label='Build Prefix' ]
           [@ww.param name='value']${repository.getBuildPrefix()?if_exists}[/@ww.param]
        [/@ww.label]
        [@ww.label label='View Tag' ]
           [@ww.param name='value']${repository.getViewTag()?if_exists}[/@ww.param]
        [/@ww.label]
        [@ww.label label='View Storage Directory' ]
           [@ww.param name='value']${repository.getViewStorageDir()?if_exists}[/@ww.param]
        [/@ww.label]
        [@ww.label label='Build Stream' ]
           [@ww.param name='value']${repository.getBuildStream()?if_exists}[/@ww.param]
        [/@ww.label]
        [@ww.label label='View Location' ]
           [@ww.param name='value']${repository.getViewLocation()?if_exists}[/@ww.param]
        [/@ww.label]
        [@ww.label label='Dynamic View' ]
           [@ww.param name='value']${build.buildDefinition.customConfiguration.get('custom.repository.cc.dynamicView')?if_exists}[/@ww.param]
        [/@ww.label]
	    [@ww.label label='Load Rules' ]
           [@ww.param name='value']${repository.getLoadRules()?if_exists}[/@ww.param]
        [/@ww.label]
    [/@ui.bambooInfoDisplay]

[/#if]
    
